---
- name:
  hosts: all
  vars:
        ansible_network_os: fadcos
        ansible_user: ansible
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Manage nat pool
      fadcos_nat_pool:
        action: delete
        name: natpool
        interface: port1
        iptype: ipv4
        ipstart: 192.168.2.101
        ipend: 192.168.2.109

