---
- name:
  hosts: all
  vars:
        ansible_network_os: fadcos
        ansible_user: ansible
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Manage system setting
      fadcos_system_setting:
       idle_timeout: 78
       config_sync: disable

